input {
  # Принимаем логи по UDP/TCP от Docker или напрямую
  gelf {
    port => 12201
    type => "docker"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fastapi-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Для отладки в консоли
}